### ISSUE TITLE
Merge both images2gif_*.py scripts into one

### ISSUE THREAD

**Issue by niroyb** [JuanPotato/Legofy#93]
This makes maintenance easier.

**Comment by CasualBeer** [comment]
Yep, That's something to be done. I plan to make a Python 2 /3 compatible version of images2gif but it requires specific handling of binary data.

Because of several reasons I won't be able to do that until "after Christmas" so if you have any suggestions leave it here : https://github.com/CasualBeer/images2gif

If I manage to achieve stable release I'll make I request to put it on pypi as separate project (the original has been pretty much abandoned, but I have to contact the rightful owner and confirm it). There are some forks on github and bitbucket , perhaps there is still someone interested in maintaining it.
